# Generated by Django 4.2 on 2024-02-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="iconSkill",
            field=models.ImageField(blank=True, upload_to="media"),
        ),
    ]
